[project]
name = "rooms"
version = "0.1.0"
description = "Welcome to all my trading rooms!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = ["tape", "replay", "lab", "desk"]
