[project]
name = "desk"
version = "0.1.0"
description = "The desk that gathers all the pieces together."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["plotly>=6.3.1"]

[tool.pyright]
venv = ".venv"
venvPath = "../"
typeCheckingMode = "standard"
