name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-packages --dev

    - name: Run tests
      run: uv run python -m pytest
      continue-on-error: true  # Remove when tests are added

    - name: Lint with flake8
      run: uv run python -m flake8 .
      continue-on-error: true  # Adjust rules as needed

    - name: Format with Black
      run: uv run python -m black --check .

    - name: Sort imports with isort
      run: uv run python -m isort --check-only .

    - name: Type check with basedpyright
      run: uv run python -m pyright .
      continue-on-error: true  # Adjust config as needed
